version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    command: python app.py

  test:
    build: .
    container_name: flask_app_test
    command: pytest test_app.py
    depends_on:
      - web
